name: Deadbolt-Reloaded
version: ${project.version}
main: net.tylers1066.DeadboltReloaded
api-version: 1.12
softdepend: [ Movecraft ]
authors: [ TylerS1066 ]
description: Deadbolt, Reloaded
website: https://github.com/TylerS1066/Deadbolt-Reloaded/

commands:
  deadbolt:
    description: Access to the Deadbolt plugin via commands.
    aliases: db

permissions:
  deadbolt.*:
    description: All user and admin functionality
    default: op
    children:
      deadbolt.user.*: true
      deadbolt.admin.*: true
  deadbolt.user.*:
    description: All user functionality
    default: op
    children:
      deadbolt.user.color: true
      deadbolt.user.create.*: true
  deadbolt.user.color:
    description: Allows coloring of signs
    default: op
  deadbolt.user.create.*:
    description: Allows protection of all chests, dispensers, furnaces, doors, and trapdoors
    default: true
    children:
      deadbolt.user.create.chest: true
      deadbolt.user.create.dispenser: true
      deadbolt.user.create.door: true
      deadbolt.user.create.furnace: true
      deadbolt.user.create.trapdoor: true
      deadbolt.user.create.fencegate: true
      deadbolt.user.create.dropper: true
      deadbolt.user.create.other: true
  deadbolt.user.create.chest:
    description: Allows user protection of chests
    default: true
  deadbolt.user.create.dispenser:
    description: Allows user protection of dispensers
    default: true
  deadbolt.user.create.door:
    description: Allows user protection of doors
    default: true
  deadbolt.user.create.furnace:
    description: Allows user protection of furnaces
    default: true
  deadbolt.user.create.trapdoor:
    description: Allows user protection of trapdoors
    default: true
  deadbolt.user.create.fencegate:
    description: Allows user protection of fencegates
    default: true
  deadbolt.user.create.dropper:
    description: Allows user protection of droppers
    default: true
  deadbolt.user.create.other:
    description: Allows user protection of other containers
    default: true
  deadbolt.admin.*:
    description: Allows for all admin functionality
    default: op
    children:
      deadbolt.admin.create: true
      deadbolt.admin.break: true
      deadbolt.admin.bypass: true
      deadbolt.admin.commands: true
      deadbolt.admin.snoop: true
  deadbolt.admin.create:
    description: Allows admin protection of all for other users and of all types
    default: op
    children:
      deadbolt.user.create.*: true
  deadbolt.admin.break:
    description: Allows admin breaking of protected blocks
    default: op
  deadbolt.admin.bypass:
    description: Allows admin usage of protected doors and trapdoors
    default: op
  deadbolt.admin.commands:
    description: Allows admin usage of commands on user blocks
    default: op
  deadbolt.admin.snoop:
    description: Allows admin usage of protected blocks
    default: op
  deadbolt.broadcast.*:
    description: Receives all notifications of admin overrides
    default: op
    children:
      deadbolt.broadcast.break: true
      deadbolt.broadcast.snoop: true
      deadbolt.broadcast.bypass: true
    deadbolt.broadcast.break:
      description: Receives notifications of admin override block breaks
      default: op
    deadbolt.broadcast.snoop:
      description: receives notifications of admin override container snoops
      default: op
    deadbolt.broadcast.bypass:
      description: receives notifications of admin override bypasses
      default: op