name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Deadbolt-Reloaded
      uses: actions/checkout@v2
      with:
        path: Deadbolt-Reloaded
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    
    # Build Ultimate-FactionsChat
    - name: Build Deadbolt-Reloaded
      run: mvn -B package -T 1C --file Deadbolt-Reloaded/pom.xml

    - name: Stage jar
      run: mkdir staging && cp Deadbolt-Reloaded/target/Deadbolt-Reloaded.jar staging
    - name: Rename jar
      run: mv staging/Deadbolt-Reloaded*.jar staging/Deadbolt-Reloaded_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: Deadbolt-Reloaded_Dev-Build
        path: staging/Deadbolt-Reloaded_*.jar
